# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('receive_date', models.DateTimeField(verbose_name='date message received')),
                ('set_date', models.DateTimeField(verbose_name='date scheduled for delivery')),
                ('message_body', models.CharField(max_length=255)),
                ('message_email', models.CharField(max_length=255)),
            ],
        ),
    ]
